# first we print the list of future Makers
puts "Karin Nielsen"
puts "Christopher Batts"
puts "Nick Dyer"
puts "Edward Byne"
puts "Alex Blease"
puts "Ben Hutchinson"
puts "Victoria Stepanovna"
puts "Ayo Obembe"
puts "Yvette Cook"
puts "Pavel Redics"
puts "Dale Stevens"
puts "Alan Bridger"
puts "Clare Trembath"
puts "Denise Yu"
puts "Ella Schofield"
puts "Tim Scully"
puts "Izzy Markwick"
puts "Simon Lange"
puts "Mishal I"
puts "Georgia Amici"
puts "Claudia B"
puts "Chris Handley"
# Then we print the total
print "Overall, we have "
# Print does not add new line characters
print 22
print " students."
